### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by ErinUntermeyer** [gabichuelas/crate#16]
This is one I've used before. Do y'all have any others you'd prefer?

# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
`Your message here`
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other, Please explain:
`Your message here`
## Has This Been Tested?
- [ ] No
- [ ] Yes
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration:
`Your message here`
# Message for reviewer:
`Your message here`
# Checklist:
- [ ] My code has no unused/commented out code
- [ ] My code has no console logs
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas

**Comment by gabichuelas** [comment]
@ErinUntermeyer My last project group used this (it might be a little more flexible and quick):

#### Description
_what does this PR accomplish and what did you change/update/delete_
_what sad paths have you covered in your testing_
_specify any bugs or details to come back to_

#### Closes issue(s)
_reference issue number(s) so that the PR is linked to the issue(s) related to this PR_

* delete the italicized lines when submitting your PR
